data_path: /home/dinh/my_sfm/test_data
database_path: /home/dinh/my_sfm/test_data/database.db
images_path: /home/dinh/my_sfm/test_data/test_images

outlier_filtering:
  max_reproj_error: 8.0
  min_tri_angle: 1.5
